/**
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.0-sw2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SaqueEPagueSonda) {
      root.SaqueEPagueSonda = {};
    }
    root.SaqueEPagueSonda.SondaRespInfTransacao = factory(root.SaqueEPagueSonda.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SondaRespInfTransacao model module.
   * @module model/SondaRespInfTransacao
   * @version 1.1.0-sw2
   */

  /**
   * Constructs a new <code>SondaRespInfTransacao</code>.
   * Objeto de resposta que contem o estado da transação sondada. Caso não encontre a transação vai retornar estado pendente.
   * @alias module:model/SondaRespInfTransacao
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SondaRespInfTransacao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SondaRespInfTransacao} obj Optional instance to populate.
   * @return {module:model/SondaRespInfTransacao} The populated <code>SondaRespInfTransacao</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
    }
    return obj;
  }

  /**
   * Status da transação nos sistemas da Saque e Pague (F = confirmada, C = cancelada, P = pendente). Para casos de teste usar até 10 para retorno cancelado, até 20 para estado confirmado e o resto pendente.
   * @member {String} status
   */
  exports.prototype['status'] = undefined;



  return exports;
}));


