/**
 * Sonda Saque e Pague
 * Modelo de API para o serviço de sonda da Saque e Pague
 *
 * OpenAPI spec version: 1.0.1
 * Contact: captura_atm@saqueepague.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SondaSaqueEPague) {
      root.SondaSaqueEPague = {};
    }
    root.SondaSaqueEPague.SondaReqInfTransacao = factory(root.SondaSaqueEPague.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SondaReqInfTransacao model module.
   * @module model/SondaReqInfTransacao
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>SondaReqInfTransacao</code>.
   * @alias module:model/SondaReqInfTransacao
   * @class
   * @param dataLocal {String} Hora local da transação desejada (yyyy-mm-dd)
   * @param horaLocal {String} Hora local da transação desejada (hh:mm:ss)
   * @param nsuTransacao {String} NSU da transação desejada
   */
  var exports = function(dataLocal, horaLocal, nsuTransacao) {
    var _this = this;

    _this['dataLocal'] = dataLocal;
    _this['horaLocal'] = horaLocal;

    _this['nsuTransacao'] = nsuTransacao;
  };

  /**
   * Constructs a <code>SondaReqInfTransacao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SondaReqInfTransacao} obj Optional instance to populate.
   * @return {module:model/SondaReqInfTransacao} The populated <code>SondaReqInfTransacao</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dataLocal')) {
        obj['dataLocal'] = ApiClient.convertToType(data['dataLocal'], 'String');
      }
      if (data.hasOwnProperty('horaLocal')) {
        obj['horaLocal'] = ApiClient.convertToType(data['horaLocal'], 'String');
      }
      if (data.hasOwnProperty('nsuSonda')) {
        obj['nsuSonda'] = ApiClient.convertToType(data['nsuSonda'], 'String');
      }
      if (data.hasOwnProperty('nsuTransacao')) {
        obj['nsuTransacao'] = ApiClient.convertToType(data['nsuTransacao'], 'String');
      }
    }
    return obj;
  }

  /**
   * Hora local da transação desejada (yyyy-mm-dd)
   * @member {String} dataLocal
   */
  exports.prototype['dataLocal'] = undefined;
  /**
   * Hora local da transação desejada (hh:mm:ss)
   * @member {String} horaLocal
   */
  exports.prototype['horaLocal'] = undefined;
  /**
   * NSU da transação de sonda
   * @member {String} nsuSonda
   */
  exports.prototype['nsuSonda'] = undefined;
  /**
   * NSU da transação desejada
   * @member {String} nsuTransacao
   */
  exports.prototype['nsuTransacao'] = undefined;



  return exports;
}));


