/**
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1-sw2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SaqueEPagueSonda) {
      root.SaqueEPagueSonda = {};
    }
    root.SaqueEPagueSonda.SondaReqTransacao = factory(root.SaqueEPagueSonda.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SondaReqTransacao model module.
   * @module model/SondaReqTransacao
   * @version 1.1.1-sw2
   */

  /**
   * Constructs a new <code>SondaReqTransacao</code>.
   * Objeto de requisição que contem informações da transação sondada e procura o último estado da mesma por um período retroativo de 7 dias.
   * @alias module:model/SondaReqTransacao
   * @class
   * @param dataLocal {String} Data máxima da transação desejada (yyyy-mm-dd) para procurar o NSU em até 7 dias antes desta data/horário. Obs. Campo será tirado de versões futuras, mas ainda necessário e mantido por retro-compatibilidade.
   * @param horaLocal {String} Hora máxima da transação desejada (hh-mm-ss) para procurar o NSU em até 7 dias antes desta data/horário. Obs. Campo será tirado de versões futuras, mas ainda necessário e mantido por retro-compatibilidade.
   * @param nsuSonda {Number} NSU da transação de sonda. Necessário para controle interno e rastreabilidade das requisições.
   * @param nsuTransacao {Number} NSU da transação desejada. Gerado pelo sistema da SEP. Para casos de teste usar até 10 para retorno cancelado, até 20 para estado confirmado e o resto pendente.
   */
  var exports = function(dataLocal, horaLocal, nsuSonda, nsuTransacao) {
    var _this = this;

    _this['dataLocal'] = dataLocal;
    _this['horaLocal'] = horaLocal;
    _this['nsuSonda'] = nsuSonda;
    _this['nsuTransacao'] = nsuTransacao;
  };

  /**
   * Constructs a <code>SondaReqTransacao</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SondaReqTransacao} obj Optional instance to populate.
   * @return {module:model/SondaReqTransacao} The populated <code>SondaReqTransacao</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dataLocal')) {
        obj['dataLocal'] = ApiClient.convertToType(data['dataLocal'], 'String');
      }
      if (data.hasOwnProperty('horaLocal')) {
        obj['horaLocal'] = ApiClient.convertToType(data['horaLocal'], 'String');
      }
      if (data.hasOwnProperty('nsuSonda')) {
        obj['nsuSonda'] = ApiClient.convertToType(data['nsuSonda'], 'Number');
      }
      if (data.hasOwnProperty('nsuTransacao')) {
        obj['nsuTransacao'] = ApiClient.convertToType(data['nsuTransacao'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Data máxima da transação desejada (yyyy-mm-dd) para procurar o NSU em até 7 dias antes desta data/horário. Obs. Campo será tirado de versões futuras, mas ainda necessário e mantido por retro-compatibilidade.
   * @member {String} dataLocal
   */
  exports.prototype['dataLocal'] = undefined;
  /**
   * Hora máxima da transação desejada (hh-mm-ss) para procurar o NSU em até 7 dias antes desta data/horário. Obs. Campo será tirado de versões futuras, mas ainda necessário e mantido por retro-compatibilidade.
   * @member {String} horaLocal
   */
  exports.prototype['horaLocal'] = undefined;
  /**
   * NSU da transação de sonda. Necessário para controle interno e rastreabilidade das requisições.
   * @member {Number} nsuSonda
   */
  exports.prototype['nsuSonda'] = undefined;
  /**
   * NSU da transação desejada. Gerado pelo sistema da SEP. Para casos de teste usar até 10 para retorno cancelado, até 20 para estado confirmado e o resto pendente.
   * @member {Number} nsuTransacao
   */
  exports.prototype['nsuTransacao'] = undefined;



  return exports;
}));


