/**
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.0-sw2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SondaRespInfTransacao'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SondaRespInfTransacao'));
  } else {
    // Browser globals (root is window)
    if (!root.SaqueEPagueSonda) {
      root.SaqueEPagueSonda = {};
    }
    root.SaqueEPagueSonda.SondaResp = factory(root.SaqueEPagueSonda.ApiClient, root.SaqueEPagueSonda.SondaRespInfTransacao);
  }
}(this, function(ApiClient, SondaRespInfTransacao) {
  'use strict';




  /**
   * The SondaResp model module.
   * @module model/SondaResp
   * @version 1.1.0-sw2
   */

  /**
   * Constructs a new <code>SondaResp</code>.
   * Objeto de resposta da sonda, contém o objeto da transação sondada. Caso não encontre a transação vai retornar estado pendente.
   * @alias module:model/SondaResp
   * @class
   * @param infTransacao {module:model/SondaRespInfTransacao} 
   */
  var exports = function(infTransacao) {
    var _this = this;

    _this['InfTransacao'] = infTransacao;
  };

  /**
   * Constructs a <code>SondaResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SondaResp} obj Optional instance to populate.
   * @return {module:model/SondaResp} The populated <code>SondaResp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('InfTransacao')) {
        obj['InfTransacao'] = SondaRespInfTransacao.constructFromObject(data['InfTransacao']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SondaRespInfTransacao} InfTransacao
   */
  exports.prototype['InfTransacao'] = undefined;



  return exports;
}));


