/**
 * Sonda Saque e Pague
 * Modelo de API para o serviço de sonda da Saque e Pague
 *
 * OpenAPI spec version: 1.0.1
 * Contact: captura_atm@saqueepague.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SondaRespInfTransacao'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SondaRespInfTransacao'));
  } else {
    // Browser globals (root is window)
    if (!root.SondaSaqueEPague) {
      root.SondaSaqueEPague = {};
    }
    root.SondaSaqueEPague.SondaResp = factory(root.SondaSaqueEPague.ApiClient, root.SondaSaqueEPague.SondaRespInfTransacao);
  }
}(this, function(ApiClient, SondaRespInfTransacao) {
  'use strict';




  /**
   * The SondaResp model module.
   * @module model/SondaResp
   * @version 1.0.1
   */

  /**
   * Constructs a new <code>SondaResp</code>.
   * @alias module:model/SondaResp
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>SondaResp</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SondaResp} obj Optional instance to populate.
   * @return {module:model/SondaResp} The populated <code>SondaResp</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('InfTransacao')) {
        obj['InfTransacao'] = SondaRespInfTransacao.constructFromObject(data['InfTransacao']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SondaRespInfTransacao} InfTransacao
   */
  exports.prototype['InfTransacao'] = undefined;



  return exports;
}));


