/**
 * Sonda Saque e Pague
 * Modelo de API para o serviço de sonda da Saque e Pague
 *
 * OpenAPI spec version: 1.0.1
 * Contact: captura_atm@saqueepague.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.SondaSaqueEPague) {
      root.SondaSaqueEPague = {};
    }
    root.SondaSaqueEPague.ActuatorControllerApi = factory(root.SondaSaqueEPague.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * ActuatorController service.
   * @module api/ActuatorControllerApi
   * @version 1.0.1
   */

  /**
   * Constructs a new ActuatorControllerApi. 
   * @alias module:api/ActuatorControllerApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getStatusUsingGET operation.
     * @callback module:api/ActuatorControllerApi~getStatusUsingGETCallback
     * @param {String} error Error message, if any.
     * @param {Object.<String, {'String': 'String'}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * getStatus
     * @param {module:api/ActuatorControllerApi~getStatusUsingGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Object.<String, {'String': 'String'}>}
     */
    this.getStatusUsingGET = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['*/*'];
      var returnType = {'String': 'String'};

      return this.apiClient.callApi(
        '/actuator/health', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
