/**
 * Sonda Saque e Pague
 * Modelo de API para o serviço de sonda da Saque e Pague
 *
 * OpenAPI spec version: 1.0.1
 * Contact: captura_atm@saqueepague.com.br
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SondaSaqueEPague);
  }
}(this, function(expect, SondaSaqueEPague) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SondaSaqueEPague.SondaRespInfTransacao();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SondaRespInfTransacao', function() {
    it('should create an instance of SondaRespInfTransacao', function() {
      // uncomment below and update the code to test SondaRespInfTransacao
      //var instance = new SondaSaqueEPague.SondaRespInfTransacao();
      //expect(instance).to.be.a(SondaSaqueEPague.SondaRespInfTransacao);
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SondaSaqueEPague.SondaRespInfTransacao();
      //expect(instance).to.be();
    });

  });

}));
