/**
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.0-sw2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SaqueEPagueSonda);
  }
}(this, function(expect, SaqueEPagueSonda) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SaqueEPagueSonda.SondaReqTerminal();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SondaReqTerminal', function() {
    it('should create an instance of SondaReqTerminal', function() {
      // uncomment below and update the code to test SondaReqTerminal
      //var instance = new SaqueEPagueSonda.SondaReqTerminal();
      //expect(instance).to.be.a(SaqueEPagueSonda.SondaReqTerminal);
    });

    it('should have the property codEstab (base name: "codEstab")', function() {
      // uncomment below and update the code to test the property codEstab
      //var instance = new SaqueEPagueSonda.SondaReqTerminal();
      //expect(instance).to.be();
    });

  });

}));
