/**
 * Saque e Pague Sonda
 * Modelo de API para o serviço de sonda da Saque e Pague. Parceiro pode requisitar o último estado de uma transação (cancelada, confirmada ou pendente) através das chamadas desta API. Caso não encontre a transação, o serviço retorna o estado pendente.
 *
 * OpenAPI spec version: 1.1.1-sw2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SaqueEPagueSonda);
  }
}(this, function(expect, SaqueEPagueSonda) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SaqueEPagueSonda.SondaReqTransacao();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SondaReqTransacao', function() {
    it('should create an instance of SondaReqTransacao', function() {
      // uncomment below and update the code to test SondaReqTransacao
      //var instance = new SaqueEPagueSonda.SondaReqTransacao();
      //expect(instance).to.be.a(SaqueEPagueSonda.SondaReqTransacao);
    });

    it('should have the property dataLocal (base name: "dataLocal")', function() {
      // uncomment below and update the code to test the property dataLocal
      //var instance = new SaqueEPagueSonda.SondaReqTransacao();
      //expect(instance).to.be();
    });

    it('should have the property horaLocal (base name: "horaLocal")', function() {
      // uncomment below and update the code to test the property horaLocal
      //var instance = new SaqueEPagueSonda.SondaReqTransacao();
      //expect(instance).to.be();
    });

    it('should have the property nsuSonda (base name: "nsuSonda")', function() {
      // uncomment below and update the code to test the property nsuSonda
      //var instance = new SaqueEPagueSonda.SondaReqTransacao();
      //expect(instance).to.be();
    });

    it('should have the property nsuTransacao (base name: "nsuTransacao")', function() {
      // uncomment below and update the code to test the property nsuTransacao
      //var instance = new SaqueEPagueSonda.SondaReqTransacao();
      //expect(instance).to.be();
    });

  });

}));
